name: release
on:
  push:
    tags:
      - v*
permissions:
  contents: write
  id-token: write
  attestations: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update app_version
        shell: bash
        run: |
          pushed_tag=${GITHUB_REF#refs/tags/}
          if [[ ! $pushed_tag =~ v[0-9]+.[0-9]+.[0-9] ]]; then
              echo invalid version string. expected format v1.2.3.
              exit 1
          fi
          sed -i -e "s/.*/$pushed_tag/" ./versions/app_version
          git update-index --skip-worktree ./versions/app_version
      - uses: cli/gh-extension-precompile@v2
        with:
          generate_attestations: true
          go_version_file: go.mod
